### ISSUE TITLE
Link site, angular no azure

### ISSUE THREAD

**Issue by CassiaAl** [cyz/vamos-juntas#1]
https://github.com/CassiaAl/produto

https://happy-sea-08ed3b310.azurestaticapps.net

**Comment by cyz** [comment]
Oi @CassiaAl , por favor, envie um e-mail para womakerscodeorg@gmail.com com o assunto "Mentoria Hacking de Carreira" e junto, envie uma cópia do seu plano de carreira e três perguntas que gostaria que eu respondesse na mentoria.

aviso: estou de férias essa semana e só responderei depois do dia 9/07, ok?

**Comment by CassiaAl** [comment]
OIii, sim, obrigada S2S2S2
