### ISSUE TITLE
Links para as páginas que desenvolvi e hospedei no Azure 

### ISSUE THREAD

**Issue by Trsouza** [cyz/vamos-juntas#2]
Achei muito prático o processo de deploy. 
Compactei as imagens, porém ainda ficou um pouco lento o carregamento. 

https://white-tree-03dc25110.azurestaticapps.net
https://happy-ocean-06300dc10.azurestaticapps.net

**Comment by cyz** [comment]
Oi @Trsouza , por favor, envie um e-mail para womakerscodeorg@gmail.com com o assunto "Mentoria Hacking de Carreira" e junto, envie uma cópia do seu plano de carreira e três perguntas que gostaria que eu respondesse na mentoria.

aviso: estou de férias essa semana e só responderei depois do dia 9/07, ok?

**Comment by Trsouza** [comment]
Email enviado!
