### ISSUE TITLE
Link site e repositório

### ISSUE THREAD

**Issue by carol-cloud** [cyz/vamos-juntas#3]
[Site Azure](https://white-ground-07ac2b110.azurestaticapps.net)
[Repositório no Github](https://github.com/carol-cloud/vamos_juntas)

**Comment by cyz** [comment]
Oi @carol-cloud, por favor, envie um e-mail para womakerscodeorg@gmail.com com o assunto "Mentoria Hacking de Carreira" e junto, envie uma cópia do seu plano de carreira e três perguntas que gostaria que eu respondesse na mentoria.

aviso: estou de férias essa semana e só responderei depois do dia 9/07, ok?
